In [6]:
#Group Members:
# AJAY SAXENA
# NANDHINI P
# V S SARAN MALLADI
    

# QUESTION 1.(i) Write a code to generate five random vectors a1, a2, a3, a4, a5 ∈ R5 and verify that these set of vectors are linearly independent.
# Deliverables : Code and related results
    
import numpy as np
#generating the random vectors
a1=np.random.randint(1,100,size=(5))
a2=np.random.randint(1,100,size=(5))
a3=np.random.randint(1,100,size=(5))
a4=np.random.randint(1,100,size=(5))
a5=np.random.randint(1,100,size=(5))
print('Vectors are: \n','a1=',a1,'\n','a2=',a2,'\n','a3=',a3,'\n','a4=',a4,'\n','a5=',a5,'\n')
#Generating matrix from vectors
m=np.array([a1,a2,a3,a4,a5])
print("Matrix M is:\n",m,"\n")
#Determinant of the matrix
d=np.linalg.det(m)
d=round(d,0)
# Verifying the linearly dependence of vectors
if d==0:
    print("Vectors are linearly dependent")
else:  
    print("Determinant of the Matrix M is:",d,"and not equal to zero.\nSo vectors are linearly independent")

Vectors are: 
 a1= [92 60 68  8 50] 
 a2= [48 66 62 15 56] 
 a3= [72 81  3 95 20] 
 a4= [99 64 54 28 57] 
 a5= [31 49 48 40 39] 

Matrix M is:
 [[92 60 68  8 50]
 [48 66 62 15 56]
 [72 81  3 95 20]
 [99 64 54 28 57]
 [31 49 48 40 39]] 

Determinant of the Matrix M is: 119944982.0 and not equal to zero.
So vectors are linearly independent


In [7]:
# QUESTION 1.(ii) Write a function that applies Gram-Schmidt Algorithm on the set of vectors a1, a2, a3, a4, a5. Let the output of Gram Schmidt algorithm be the vectors q1, q2, q3, q4, q5.
# Deliverables : Code and the result vectors
import numpy as np
print("Vectors are :\na1=",a1,"\na2=",a2,"\na3=",a3,"\na4=",a4,"\na5=",a5)

M=np.array([a1,a2,a3,a4,a5])
print("\nMatrix M:\n",M)

#applying Gram Schmidt algorithm on the set of random vectors to produce orthonormal vectors
#q1=a1/np.linalg.norm(a1)
#print("\nq1=",q1,"\n")
def gramschmidt(A):
    """
    Applies the Gram-Schmidt method to A
    and returns Q and R, so Q*R = A.
    """
    R = np.zeros((A.shape[1], A.shape[1]))
    Q = np.zeros(A.shape)
    for k in range(0, A.shape[1]):
        R[k, k] = np.sqrt(np.dot(A[:, k], A[:, k]))
        Q[:, k] = A[:, k]/R[k, k]
        for j in range(k+1, A.shape[1]):
            R[k, j] = np.dot(Q[:, k], A[:, j])
            A[:, j] = A[:, j] - R[k, j]*Q[:, k]
    return Q
Q_1 = gramschmidt(M)

for a,k in enumerate(Q_1):
    new_var = "q"+str(a+1)
    globals()[new_var] = k
    print("q"+str(a+1)+"=",k)
# Just to check if q1,q2,q3,q4,q5 are vectors of unit magnitude?
print("\nq1 Norm=",round(np.linalg.norm(q1)),"\nq2 Norm=",round(np.linalg.norm(q2)),"\nq3 Norm=",round(np.linalg.norm(q3)),"\nq4 Norm=",round(np.linalg.norm(q4)),"\nq5 Norm=",round(np.linalg.norm(q5)) )   

Vectors are :
a1= [92 60 68  8 50] 
a2= [48 66 62 15 56] 
a3= [72 81  3 95 20] 
a4= [99 64 54 28 57] 
a5= [31 49 48 40 39]

Matrix M:
 [[92 60 68  8 50]
 [48 66 62 15 56]
 [72 81  3 95 20]
 [99 64 54 28 57]
 [31 49 48 40 39]]
q1= [ 0.5628833  -0.3651905   0.25877458 -0.0451754  -0.62994079]
q2= [ 0.29367825  0.53704485  0.43129097 -0.63245553  0.12598816]
q3= [ 0.44051737  0.42963588 -0.77632375  0.         -0.12598816]
q4= [ 0.60571138 -0.38667229 -0.01725164  0.09035079  0.75592895]
q5= [0.1896672  0.49408126 0.37953606 0.76798172 0.        ]

q1 Norm= 1 
q2 Norm= 1 
q3 Norm= 1 
q4 Norm= 1 
q5 Norm= 1


In [8]:
# QUESTION 1.(iii) Write a code to create a matrix Q ∈ R 5×5 with q1, q2, q3, q4, q5 as the five columns. Then create a matrix B = Q⊤Q.
# Deliverables : Code and the matrix B

import numpy as np
#five column vectors as q1,q2,q3,q4,q5 
# q1=np.array(q1)
q1=q1.reshape(5,1)
q2=q2.reshape(5,1)
q3=q3.reshape(5,1)
q4=q4.reshape(5,1)
q5=q5.reshape(5,1)
print("q1=\n",q1,"\nq2=\n",q2,"\nq3=\n",q3,"\nq4=\n",q4,"\nq5=\n",q5)

# Matrix Q created from Column vectors q1,q2,q3,q4,q5
Q=np.concatenate([q1,q2,q3,q4,q5],axis=1).reshape(5,5)
print("\nMatrix Q is:\n",Q)
#Create Q-transpose
QT=Q.transpose()
print("\nMatrix QT:\n",QT)

# Multiplication of QT & Q          
C = np.zeros((A.shape[0],B.shape[1]),dtype = float)
for row in range(len(QT)):
    for col in range(len(Q)):
                     for elt in range(len(Q)):
                         C[row, col] += QT[row, elt] * Q[elt, col]
print("\nMatrix B=QTQ:\n",C)
#Just to check if the codes for multiplication is correct, lets get B=QTQ through matmul?
print("\nMatrix B=QTQ:\n",np.matmul(QT,Q))



q1=
 [[ 0.5628833 ]
 [-0.3651905 ]
 [ 0.25877458]
 [-0.0451754 ]
 [-0.62994079]] 
q2=
 [[ 0.29367825]
 [ 0.53704485]
 [ 0.43129097]
 [-0.63245553]
 [ 0.12598816]] 
q3=
 [[ 0.44051737]
 [ 0.42963588]
 [-0.77632375]
 [ 0.        ]
 [-0.12598816]] 
q4=
 [[ 0.60571138]
 [-0.38667229]
 [-0.01725164]
 [ 0.09035079]
 [ 0.75592895]] 
q5=
 [[0.1896672 ]
 [0.49408126]
 [0.37953606]
 [0.76798172]
 [0.        ]]

Matrix Q is:
 [[ 0.5628833   0.29367825  0.44051737  0.60571138  0.1896672 ]
 [-0.3651905   0.53704485  0.42963588 -0.38667229  0.49408126]
 [ 0.25877458  0.43129097 -0.77632375 -0.01725164  0.37953606]
 [-0.0451754  -0.63245553  0.          0.09035079  0.76798172]
 [-0.62994079  0.12598816 -0.12598816  0.75592895  0.        ]]

Matrix QT:
 [[ 0.5628833  -0.3651905   0.25877458 -0.0451754  -0.62994079]
 [ 0.29367825  0.53704485  0.43129097 -0.63245553  0.12598816]
 [ 0.44051737  0.42963588 -0.77632375  0.         -0.12598816]
 [ 0.60571138 -0.38667229 -0.01725164  0.09035079  0.75592895]


In [9]:
# QUESTION 1.(iv) Write a code to calculate the value of ∥B − I5∥F where ∥ · ∥F is the matrix Frobenius norm. 
# Deliverables : Code and the display of the value calculated

from numpy import linalg as LA
print("B=\n",C)
#Generate I5
I5=np.identity(5)
print("\nI5=\n",I5)
#Frobenious Norm
print("\nFrobenious Norm ||B-I5||F=",round(LA.norm(B-I5)))

B=
 [[ 9.16032210e-01  2.99963996e-02 -3.04668452e-02 -2.58252686e-03
  -1.01528711e-02]
 [ 2.99963996e-02  9.76548999e-01  9.40965642e-03  8.78657407e-04
  -9.78885768e-04]
 [-3.04668452e-02  9.40965642e-03  9.97194125e-01  1.88528571e-02
   1.18387321e-03]
 [-2.58252686e-03  8.78657407e-04  1.88528571e-02  1.09629119e+00
  -1.33238135e-02]
 [-1.01528711e-02 -9.78885768e-04  1.18387321e-03 -1.33238135e-02
   1.01393347e+00]]

I5=
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Frobenious Norm ||B-I5||F= 0


In [10]:
#alternate method to do the above all
import numpy as np
np.random.seed(100)
dim=5
A=[]
for i in range(dim):
    A.append(np.random.randint(1,10, size=dim)) 
A = np.array(A).astype("float")
print("Input Matrix: \n", A)

Rank_A = np.linalg.matrix_rank(A)
print("\nVectors are Linearly " + ("In-" if Rank_A==dim else "") + "Dependent")

def gram_schmidt(A):    
    for i in range(len(A)):  
        intr_sum=0
        for j in range(i):
            intr_sum += np.dot(A[i],A[j].transpose())*A[j]                 
        A[i] -= intr_sum        
        A[i] = A[i]/np.linalg.norm(A[i])
    print("\nGS by Calculation: \n", np.round(A,3))
    return A

Q = gram_schmidt(A)

import sympy as sym
C = [sym.Matrix(v) for v in A]
C = sym.GramSchmidt(C, True)
C = np.array(C).reshape(5,5).astype('f')
print("\nGS by Inbuilt Method: \n", np.round(C,3))

B = np.round(np.matmul(Q.transpose(), Q),10)
print("\nB = Qt.Q: \n", B)

N = B-np.eye(5)
print("\nFrobenius Norm of B-I5:", np.round(np.linalg.norm(N), 10))

Input Matrix: 
 [[9. 9. 4. 8. 8.]
 [1. 5. 3. 6. 3.]
 [3. 3. 2. 1. 9.]
 [5. 1. 7. 3. 5.]
 [2. 6. 4. 5. 5.]]

Vectors are Linearly In-Dependent

GS by Calculation: 
 [[ 0.514  0.514  0.229  0.457  0.457]
 [-0.726  0.223  0.284  0.568 -0.144]
 [-0.402 -0.135  0.104 -0.297  0.849]
 [ 0.196 -0.493  0.843  0.001 -0.088]
 [-0.092  0.651  0.382 -0.617 -0.203]]

GS by Inbuilt Method: 
 [[ 0.514  0.514  0.229  0.457  0.457]
 [-0.726  0.223  0.284  0.568 -0.144]
 [-0.402 -0.135  0.104 -0.297  0.849]
 [ 0.196 -0.493  0.843  0.001 -0.088]
 [-0.092  0.651  0.382 -0.617 -0.203]]

B = Qt.Q: 
 [[ 1. -0. -0.  0.  0.]
 [-0.  1. -0.  0.  0.]
 [-0. -0.  1. -0.  0.]
 [ 0.  0. -0.  1. -0.]
 [ 0.  0.  0. -0.  1.]]

Frobenius Norm of B-I5: 0.0
